import os

DB_USERNAME = os.environ['DB_USERNAME']
DB_PASSWORD = os.environ['DB_PASSWORD']
DB_HOST = os.environ['DB_HOST']
DB_PORT = os.environ['DB_PORT']
WEATHER_STATION_MAC = os.environ['WEATHER_STATION_MAC']
OUTSIDE_MODULE_MAC = os.environ['OUTSIDE_MODULE_MAC']
RAIN_MODULE_MAC = os.environ['RAIN_MODULE_MAC']
NETATMO_USERNAME = os.environ['NETATMO_USERNAME']
NETATMO_PASSWORD = os.environ['NETATMO_PASSWORD']
NETATMO_CLIENT_ID = os.environ['NETATMO_CLIENT_ID']
NETATMO_CLIENT_SECRET = os.environ['NETATMO_CLIENT_SECRET']



